# Generated by Django 4.2.1 on 2025-04-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0014_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionuser',
            name='adhar_card',
        ),
        migrations.RemoveField(
            model_name='auctionuser',
            name='adhar_number',
        ),
        migrations.RemoveField(
            model_name='auctionuser',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='auctionuser',
            name='pan_number',
        ),
    ]
